version: "3.9"
services:
  next:
    build:
      context: ./
      # target: dev
    container_name: next
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always
